name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Setup protoc
      run: apt-get -y install protobuf-compiler

    - name: Go fmt
      run: make gofmt
    
    - name: Go vet
      run: make govet

    - name: Build cli
      run: make build-cli

    - name: Test
      run: make test
